import { NextResponse } from "next/server";
import { getCurrentUser, requireAdmin } from "@/lib/auth";
import { getDb, serialize } from "@/lib/mongodb";

type Answer = { questionId: string; answer: string };
const clean = (value: unknown, max: number) => typeof value === "string" ? value.replace(/[<>]/g, "").trim().slice(0, max) : "";

export async function GET(request: Request) {
  try { await requireAdmin(); const params = new URL(request.url).searchParams; const from = params.get("from"); const to = params.get("to"); const filter: Record<string, unknown> = {}; if (from || to) filter.createdAt = { ...(from ? { $gte: new Date(`${from}T00:00:00`) } : {}), ...(to ? { $lt: new Date(`${to}T23:59:59.999`) } : {}) }; const docs = await (await getDb()).collection("feedbacks").find(filter).sort({ createdAt: -1 }).limit(500).toArray(); return NextResponse.json({ feedback: docs.map(doc => serialize(doc as typeof doc & { _id: import("mongodb").ObjectId })) }); } catch (error) { const unauthorized = error instanceof Error && error.message === "UNAUTHORIZED"; return NextResponse.json({ error: unauthorized ? "Нэвтрэх шаардлагатай." : "Санал хүсэлтийг ачаалж чадсангүй." }, { status: unauthorized ? 401 : 500 }); }
}

export async function POST(request: Request) {
  try { const user = await getCurrentUser(); const body = await request.json(); const answers: Answer[] = Array.isArray(body.answers) ? body.answers.filter((answer: unknown): answer is Answer => Boolean(answer) && typeof answer === "object" && typeof (answer as Answer).questionId === "string" && typeof (answer as Answer).answer === "string").map((answer: Answer) => ({ questionId: answer.questionId, answer: clean(answer.answer, 3000) })) : []; const rating = Number(body.rating || answers.find((answer: Answer) => answer.questionId === "rating")?.answer); const comment = clean(body.comment, 3000); const guestName = clean(body.name, 80); const guestPhone = typeof body.phone === "string" && /^\d{8}$/.test(body.phone) ? body.phone : ""; if (!comment && !answers.length) return NextResponse.json({ error: "Сэтгэгдлээ оруулна уу." }, { status: 400 }); if (body.rating !== undefined && (!Number.isInteger(rating) || rating < 1 || rating > 5)) return NextResponse.json({ error: "Үнэлгээ 1-5 хооронд байна." }, { status: 400 }); const result = await (await getDb()).collection("feedbacks").insertOne({ ...(user ? { userId: user.id, userPhone: user.phone, userName: user.name } : { userPhone: guestPhone, userName: guestName || "Зочин" }), rating: Number.isInteger(rating) ? rating : null, answers, comment, createdAt: new Date(), status: "active" }); return NextResponse.json({ ok: true, id: result.insertedId.toString() }, { status: 201 }); } catch { return NextResponse.json({ error: "Санал илгээх үед алдаа гарлаа." }, { status: 500 }); }
}
