"use client";
import { useEffect, useRef, useState } from "react";

export default function QrStampScanner({ onScanned }: { onScanned: (phone: string) => Promise<void> }) {
  const videoRef = useRef<HTMLVideoElement>(null);
  const [active, setActive] = useState(false);
  const [message, setMessage] = useState("");
  useEffect(() => { if (!active) return; let stream: MediaStream | undefined; let timer: number | undefined; const start = async () => { try { if (!("BarcodeDetector" in window)) throw new Error("Энэ төхөөрөмж QR уншигч дэмжихгүй байна."); stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: "environment" } }); if (videoRef.current) { videoRef.current.srcObject = stream; await videoRef.current.play(); } const Detector = (window as Window & { BarcodeDetector?: new (options?: { formats: string[] }) => { detect: (source: HTMLVideoElement) => Promise<Array<{ rawValue?: string }>> } }).BarcodeDetector; if (!Detector) throw new Error("QR уншигч боломжгүй байна."); const detector = new Detector({ formats: ["qr_code"] }); const scan = async () => { if (!videoRef.current) return; const codes = await detector.detect(videoRef.current); const phone = codes[0]?.rawValue?.replace(/^ginza:user:/, ""); if (phone && /^\d{8}$/.test(phone)) { await onScanned(phone); setMessage(`${phone} дугаарт stamp нэмэгдлээ.`); setActive(false); } timer = window.setTimeout(scan, 500); }; scan(); } catch (error) { setMessage(error instanceof Error ? error.message : "Камер нээж чадсангүй."); setActive(false); } }; start(); return () => { if (timer) window.clearTimeout(timer); stream?.getTracks().forEach(track => track.stop()); }; }, [active, onScanned]); return <div className="qr-scanner"><button className="btn btn-soft" onClick={() => { setMessage(""); setActive(value => !value); }}>{active ? "QR уншилтыг зогсоох" : "QR-ээр stamp өгөх"}</button>{active && <video ref={videoRef} className="qr-camera" muted playsInline />}{message && <small>{message}</small>}</div>;
}
