import { GoogleGenAI } from "@google/genai";
import { NextResponse } from "next/server";
import { getCurrentAdmin, requireAdmin } from "@/lib/auth";
import { getDb } from "@/lib/mongodb";
type Feedback = { roomNumber?: number; rating?: number; comment?: string; answers?: { answer?: string }[]; status?: string; createdAt: Date | string };
type Analysis = { summary: string; strengths: string[]; weaknesses: string[]; recommendations: string[] };
const active = { $or: [{ status: "active" }, { status: { $exists: false } }] };
const keywords: Record<string,string[]>={"Дууны сонголт":["дуу","playlist","song"],"Дууны чанар":["дууны чанар","sound","чанар"],"Үйлчилгээ":["үйлчилгээ","ажилтан","зөөгч"],"Цэвэрлэгээ":["цэвэр","ариун","бохир"],"Тоног төхөөрөмж":["тоног","микрофон","төхөөрөмж"],"Хоол, ундаа":["хоол","ундаа","уух"],"Үнэ":["үнэ","төлбөр","үнэтэй"],"Өрөөний орчин":["өрөө","орчин","тохилог"]};
const text=(item:Feedback)=>`${item.comment||""} ${(item.answers||[]).map(answer=>answer.answer||"").join(" ")}`.trim();
const avg=(items:Feedback[])=>items.length?Number((items.reduce((sum,item)=>sum+Number(item.rating||0),0)/items.length).toFixed(1)):0;
function fallback(items:Feedback[]):Analysis { const themes=Object.entries(keywords).map(([name,words])=>({name,count:items.filter(item=>words.some(word=>text(item).toLowerCase().includes(word))).length})).filter(item=>item.count).sort((a,b)=>b.count-a.count); return {summary:items.length?`${items.length} саналд хийсэн шинжилгээгээр дундаж үнэлгээ ${avg(items)} байна.`:"Одоогоор шинжлэх санал хүсэлт хангалтгүй байна.",strengths:avg(items)>=4?["Үйлчилгээний ерөнхий үнэлгээ сайн байна."]:[],weaknesses:themes.slice(0,3).map(item=>`${item.name}-тэй холбоотой санал ${item.count} удаа давтагдсан байна.`),recommendations:themes.length?[`${themes[0].name}-ийн талаар давтагдсан саналуудыг шалгаж, бодит сайжруулалтын арга хэмжээ аваарай.`]:["Зөвлөмж гаргахад одоогоор хангалттай мэдээлэл алга."]}; }
function parse(textValue:string):Analysis|null { try { const value=JSON.parse(textValue.replace(/^```json\s*|\s*```$/g,"")); if(typeof value.summary!=="string"||!["strengths","weaknesses","recommendations"].every(key=>Array.isArray(value[key])))return null; return {summary:value.summary,strengths:value.strengths.filter((item:unknown):item is string=>typeof item==="string").slice(0,5),weaknesses:value.weaknesses.filter((item:unknown):item is string=>typeof item==="string").slice(0,5),recommendations:value.recommendations.filter((item:unknown):item is string=>typeof item==="string").slice(0,5)}; } catch { return null; } }
async function aggregate(days:number){const db=await getDb();const all=await db.collection<Feedback>("feedbacks").find(active).toArray();const now=Date.now();const items=days?all.filter(item=>now-new Date(item.createdAt).getTime()<=days*86400000):all;const rooms=await db.collection("rooms").find({}).sort({roomNumber:1}).toArray();return {total:items.length,average:avg(items),today:all.filter(item=>now-new Date(item.createdAt).getTime()<86400000).length,week:all.filter(item=>now-new Date(item.createdAt).getTime()<7*86400000).length,month:all.filter(item=>now-new Date(item.createdAt).getTime()<30*86400000).length,distribution:[1,2,3,4,5].map(rating=>({rating,count:items.filter(item=>Number(item.rating)===rating).length})),roomStats:rooms.map(room=>{const roomItems=items.filter(item=>item.roomNumber===room.roomNumber);return {roomNumber:room.roomNumber,name:room.name,count:roomItems.length,average:avg(roomItems)}}),ruleBased:fallback(items),aiItems:items.slice(-200).map(item=>({roomNumber:item.roomNumber,rating:item.rating,text:text(item)})).filter(item=>item.text)};}
export async function GET(request:Request){try{await requireAdmin();const days=Number(new URL(request.url).searchParams.get("days")||30);const data=await aggregate(Number.isFinite(days)&&days>=0?days:30);const {aiItems,...clean}=data;return NextResponse.json({...clean,feedbackForAi:undefined});}catch(error){if(error instanceof Error&&error.message==="UNAUTHORIZED")return NextResponse.json({error:"Нэвтрэх шаардлагатай."},{status:401});return NextResponse.json({error:"Шинжилгээний мэдээллийг ачаалж чадсангүй."},{status:500});}}
export async function POST(request:Request){if(!await getCurrentAdmin())return NextResponse.json({error:"Нэвтрэх шаардлагатай."},{status:401});try{const body=await request.json().catch(()=>({}));const days=Number(body.days||30);const data=await aggregate(Number.isFinite(days)&&days>=0?days:30);const base=data.ruleBased;if(!process.env.GEMINI_API_KEY||!data.aiItems.length)return NextResponse.json({source:"rule-based",analysis:base});const ai=new GoogleGenAI({apiKey:process.env.GEMINI_API_KEY});const response=await ai.models.generateContent({model:"gemini-2.5-flash-lite",contents:`Та Ginza Karaoke-ийн админд зориулсан Монгол хэлний санал хүсэлтийн шинжээч. Зөвхөн JSON буцаа: {"summary":"Ерөнхий товч дүгнэлт","strengths":["Давуу тал"],"weaknesses":["Сул тал"],"recommendations":["Хэрэгжүүлэх зөвлөмж"]}. Бодит feedback-ээс дүгнэлт гарга, байхгүй асуудлыг бүү зохио.\n${JSON.stringify(data.aiItems)}`,config:{responseMimeType:"application/json"}});const analysis=parse(response.text||"")||base;return NextResponse.json({source:analysis===base?"rule-based":"gemini",analysis});}catch(error){if(error instanceof Error&&error.message==="UNAUTHORIZED")return NextResponse.json({error:"Нэвтрэх шаардлагатай."},{status:401});return NextResponse.json({source:"rule-based",analysis:{summary:"AI шинжилгээ одоогоор ажиллахгүй байна.",strengths:[],weaknesses:[],recommendations:["Дахин оролдоно уу эсвэл rule-based шинжилгээг ашиглана уу."]}});}}
